title: Michal Krchňavý blog
url: http://blog.krchnavy.sk/
description: Dobrodruzstva vyvojara
email: michal@krchnavy.sk

encoding: utf-8
markdown: kramdown
excerpt_separator: "\n\n"

permalink: /posts/:year/:month/:day/:title

timezone: Europe/Bratislava

paginate: 15
paginate_path: "/posts/archive/page:num/"

#safe: true
lsi: false
exclude: [.gitignore, CNAME, Dockerfile, README.md]

gems: [jekyll-paginate]
