title: Michal Krchňavý blog
url: http://zemacik.github.io
description: Dobrodruzstva vyvojara
email: michal@krchnavy.sk

markdown: kramdown
excerpt_separator: "\n\n"

permalink: /blog/:year/:month/:day/:title

timezone: Europe/Bratislava

paginate: 15
paginate_path: "/blog/archive/page:num/"

safe: true
lsi: false
exclude: [.gitignore, CNAME, Dockerfile, README.md]

gems:
 - jekyll-paginate
