title: Michal Krchňavý Blog
url: http://krchnavy.sk
description: Adventures in the high-tech underbelly
email: michal@krchnavy.sk

highlighter: pygments
markdown: kramdown
excerpt_separator: "\n\n"

timezone: Europe/Bratislava

paginate: 15
paginate_path: "/blog/archive/page:num/"

safe: true
lsi: false
exclude: [.gitignore, CNAME, Dockerfile, README.md]

gems:
 - jekyll-paginate
