title: Michal Krchňavý Blog
url: http://krchnavy.sk
description: Adventures in the high-tech underbelly
email: michal@krchnavy.sk

highlighter: pygments
markdown: kramdown
excerpt_separator: "\n\n"

permalink: /blog/:year/:month/:day/:title/
timezone: Europe/Bratislava

paginate: 15

safe: true
lsi: false
exclude: [.gitignore, CNAME, Dockerfile, README.md]
